import Head from "next/head";

import Footer from "@/components/layouts/Footer";
import Header from "@/components/layouts/Header";
import Sidebar from "@/components/layouts/Sidebar";
import Breadcrumb from "@/components/layouts/Breadcrumb";

import HomeContent from "@/components/contents/HomeContent";

export const metadata = {
  title: "CMS Project",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <Head>
        <title>CMS Project</title>
        <meta name="description" content="This is CMS Project" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-1">
        {/* <Sidebar /> */}

        <div className="flex-1 flex flex-col transition-all duration-200 ease-in-out">
            {/* <Header /> */}

            <main className="flex-1 p-6 overflow-y-auto">
                <Breadcrumb title="Dashboard" link="/" />
                <HomeContent />
            </main>

            {/* <Footer /> */}
        </div>
      </div>
      
    </>
  );
}
